### ISSUE TITLE
Move the task to another column when the commit is received.

### ISSUE THREAD

**Issue by LubosRemplik** [kanboard/plugin-bitbucket-webhook#1]
As far as I understand, it is possible to open / close the task when the commit is received. Would be great if we can just change column when the commit is received.

What do you think? Any comments / ideas?

Thanks

**Comment by williamsdb** [comment]
I agree that this would be a nice to have but I have got round this by creating a board called "Maintenance" that everything goes into and I triage from there.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
