### ISSUE TITLE
assign the comentary to the Kanboard user Based on @User Name in the comentary text

### ISSUE THREAD

**Issue by thiagonatanael** [kanboard/plugin-bitbucket-webhook#4]
First of all, Nice Work!

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
