### ISSUE TITLE
Webhok is not working

### ISSUE THREAD

**Issue by vistar** [kanboard/plugin-bitbucket-webhook#5]
I add webhook to bitbucket, actions on board and commit & push with #888 message.
On page https://bitbucket.org/***/***/admin/addon/admin/bitbucket-webhooks/bb-webhooks-repo-admin I see:

`
Response from http://tasks.***/webhook/bitbucket/21/1d62395a742260738a406789366a84138ced50a1be62e8862c5cf8d0a***
HTTP status: 302
Elapsed time: 205ms
Request time: 13 minutes ago (Friday, October 6th 2017, 3:14:03 pm)
Headers
Content-Length	192
Content-Encoding	gzip
Vary	Accept-Encoding
Keep-Alive	timeout=5, max=100
Server	Apache/2.2.22
Connection	Keep-Alive
Location	https://tasks.***/index.php
Date	Fri, 06 Oct 2017 12:14:03 GMT
Content-Type	text/html; charset=iso-8859-1

Body
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://tasks.***/index.php">here</a>.</p>
</body></html>
`

and comment is not added to kanboard task.

**Comment by williamespindola** [comment]
Hi @vistar the 302 code tell us that it's redirecting to some other url. I need more information to help you.
- The status of webhook is ative on bitbucket?
- Try mark Skip certificate verification option you tasks url on comment above is http;

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
